# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: interface.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finterface.proto\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1c\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t\"t\n\x0fScheduleRequest\x12\x1a\n\x07request\x18\x01 \x01(\x0b\x32\t.ItemList\x12\x15\n\rnum_deliverer\x18\x02 \x01(\r\x12\x1c\n\titemlists\x18\x03 \x03(\x0b\x32\t.ItemList\x12\x10\n\x08\x64istance\x18\x04 \x03(\x04\"<\n\rScheduleReply\x12\x14\n\x0c\x64\x65liverer_id\x18\x01 \x01(\r\x12\x15\n\x05route\x18\x02 \x03(\x0b\x32\x06.Route\"]\n\x08ItemList\x12#\n\x05items\x18\x01 \x03(\x0b\x32\x14.ItemList.ItemsEntry\x1a,\n\nItemsEntry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"9\n\x05Route\x12\x13\n\x0bsupplier_id\x18\x01 \x01(\r\x12\x1b\n\x08itemlist\x18\x02 \x01(\x0b\x32\t.ItemList2_\n\tAlgorithm\x12\"\n\x04Ping\x12\x0c.PingRequest\x1a\n.PingReply\"\x00\x12.\n\x08Schedule\x12\x10.ScheduleRequest\x1a\x0e.ScheduleReply\"\x00\x42\x08Z\x06.;gRPCb\x06proto3')



_PINGREQUEST = DESCRIPTOR.message_types_by_name['PingRequest']
_PINGREPLY = DESCRIPTOR.message_types_by_name['PingReply']
_SCHEDULEREQUEST = DESCRIPTOR.message_types_by_name['ScheduleRequest']
_SCHEDULEREPLY = DESCRIPTOR.message_types_by_name['ScheduleReply']
_ITEMLIST = DESCRIPTOR.message_types_by_name['ItemList']
_ITEMLIST_ITEMSENTRY = _ITEMLIST.nested_types_by_name['ItemsEntry']
_ROUTE = DESCRIPTOR.message_types_by_name['Route']
PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingReply = _reflection.GeneratedProtocolMessageType('PingReply', (_message.Message,), {
  'DESCRIPTOR' : _PINGREPLY,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:PingReply)
  })
_sym_db.RegisterMessage(PingReply)

ScheduleRequest = _reflection.GeneratedProtocolMessageType('ScheduleRequest', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULEREQUEST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleRequest)
  })
_sym_db.RegisterMessage(ScheduleRequest)

ScheduleReply = _reflection.GeneratedProtocolMessageType('ScheduleReply', (_message.Message,), {
  'DESCRIPTOR' : _SCHEDULEREPLY,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:ScheduleReply)
  })
_sym_db.RegisterMessage(ScheduleReply)

ItemList = _reflection.GeneratedProtocolMessageType('ItemList', (_message.Message,), {

  'ItemsEntry' : _reflection.GeneratedProtocolMessageType('ItemsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ITEMLIST_ITEMSENTRY,
    '__module__' : 'interface_pb2'
    # @@protoc_insertion_point(class_scope:ItemList.ItemsEntry)
    })
  ,
  'DESCRIPTOR' : _ITEMLIST,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:ItemList)
  })
_sym_db.RegisterMessage(ItemList)
_sym_db.RegisterMessage(ItemList.ItemsEntry)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), {
  'DESCRIPTOR' : _ROUTE,
  '__module__' : 'interface_pb2'
  # @@protoc_insertion_point(class_scope:Route)
  })
_sym_db.RegisterMessage(Route)

_ALGORITHM = DESCRIPTOR.services_by_name['Algorithm']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\006.;gRPC'
  _ITEMLIST_ITEMSENTRY._options = None
  _ITEMLIST_ITEMSENTRY._serialized_options = b'8\001'
  _PINGREQUEST._serialized_start=19
  _PINGREQUEST._serialized_end=49
  _PINGREPLY._serialized_start=51
  _PINGREPLY._serialized_end=79
  _SCHEDULEREQUEST._serialized_start=81
  _SCHEDULEREQUEST._serialized_end=197
  _SCHEDULEREPLY._serialized_start=199
  _SCHEDULEREPLY._serialized_end=259
  _ITEMLIST._serialized_start=261
  _ITEMLIST._serialized_end=354
  _ITEMLIST_ITEMSENTRY._serialized_start=310
  _ITEMLIST_ITEMSENTRY._serialized_end=354
  _ROUTE._serialized_start=356
  _ROUTE._serialized_end=413
  _ALGORITHM._serialized_start=415
  _ALGORITHM._serialized_end=510
# @@protoc_insertion_point(module_scope)
