// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: interface.proto

package gRPC

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AlgorithmClient is the client API for Algorithm service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlgorithmClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleReply, error)
}

type algorithmClient struct {
	cc grpc.ClientConnInterface
}

func NewAlgorithmClient(cc grpc.ClientConnInterface) AlgorithmClient {
	return &algorithmClient{cc}
}

func (c *algorithmClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	out := new(PingReply)
	err := c.cc.Invoke(ctx, "/Algorithm/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *algorithmClient) Schedule(ctx context.Context, in *ScheduleRequest, opts ...grpc.CallOption) (*ScheduleReply, error) {
	out := new(ScheduleReply)
	err := c.cc.Invoke(ctx, "/Algorithm/Schedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlgorithmServer is the server API for Algorithm service.
// All implementations must embed UnimplementedAlgorithmServer
// for forward compatibility
type AlgorithmServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	Schedule(context.Context, *ScheduleRequest) (*ScheduleReply, error)
	mustEmbedUnimplementedAlgorithmServer()
}

// UnimplementedAlgorithmServer must be embedded to have forward compatible implementations.
type UnimplementedAlgorithmServer struct {
}

func (UnimplementedAlgorithmServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAlgorithmServer) Schedule(context.Context, *ScheduleRequest) (*ScheduleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Schedule not implemented")
}
func (UnimplementedAlgorithmServer) mustEmbedUnimplementedAlgorithmServer() {}

// UnsafeAlgorithmServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlgorithmServer will
// result in compilation errors.
type UnsafeAlgorithmServer interface {
	mustEmbedUnimplementedAlgorithmServer()
}

func RegisterAlgorithmServer(s grpc.ServiceRegistrar, srv AlgorithmServer) {
	s.RegisterService(&Algorithm_ServiceDesc, srv)
}

func _Algorithm_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Algorithm/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Algorithm_Schedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlgorithmServer).Schedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Algorithm/Schedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlgorithmServer).Schedule(ctx, req.(*ScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Algorithm_ServiceDesc is the grpc.ServiceDesc for Algorithm service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Algorithm_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Algorithm",
	HandlerType: (*AlgorithmServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Algorithm_Ping_Handler,
		},
		{
			MethodName: "Schedule",
			Handler:    _Algorithm_Schedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface.proto",
}
